extends: airbnb
globals:
  fetch: false
parser: babel-eslint
rules:
  react/jsx-filename-extension:
  - error
  - extensions:
    - ".js"
    - ".jsx"
  react/jsx-wrap-multilines:
  - warn
  react/destructuring-assignment:
  - warn
  react/jsx-one-expression-per-line:
  - warn
  global-require: 'off'
  no-console: 'off'
  import/no-extraneous-dependencies: 'off'
  import/extensions: 'off'
  import/no-unresolved: 'off'
  jsx-a11y/href-no-hash: 'off'
  jsx-a11y/img-has-alt: 'off'
  prefer-promise-reject-errors: 'off'
  function-paren-newline: 'off'
  operator-linebreak: 'off'
