# Note: I cannot get React Native builds to work on CircleCI 2.0 without
# persistent out of memory issues. So the android build runs on travis.
language: android
before_install:
- nvm install 8
- npm i -g npm@5.7
- node --version
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script: 
- npm install
- npm test
- npm run ci #2
- BUILD_NUM=$CIRCLE_BUILD_NUM ./scripts/version.sh
- bundle install
- bundle exec fastlane android build
