version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn
      - run: yarn run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
      - store_test_results:
          path: ~/project/artifacts/tests/junit.xml

  android:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: echo "GAMEBOARD_RELEASE_KEY_PASSWORD=${GAMEBOARD_RELEASE_KEY_PASSWORD}" >> ./android/gradle.properties
      - run: echo "GAMEBOARD_RELEASE_KEY_PASSWORD=${GAMEBOARD_RELEASE_KEY_PASSWORD}" >> ./android/gradle.properties
      - run: bundle install
      - run: bundle exec fastlane android build
      - store_artifacts:
          path: ~/project/artifacts/android
      - store_test_results:
          path: ~/project/android/reports

  ios:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/project
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      FL_OUTPUT_DIR: /Users/distiller/project/output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout:
          path: /Users/distiller/project
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      # Not using a workspace here as Node and Yarn versions
      # differ between the macOS image and the Docker containers above.
      - run: yarn
      - run: bundle install
      - run: bundle exec fastlane ios build
      - run:
          command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/results.xml
          when: always
      - store_artifacts:
          path: /Users/distiller/project/artifacts/ios
      - store_test_results:
          path: /Users/distiller/project/output/scan

workflows:
  version: 2
  node-android-ios:
    jobs:
      - build
      - android:
          requires:
            - build
      - ios:
          requires:
            - build
