version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: cd ~/project/artifacts/coverage && bash <(curl -s https://codecov.io/bash)
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
      - store_test_results:
          path: ~/project/artifacts/tests/junit.xml

  android:
    working_directory: ~/project
    environment:
      JVM_OPTS: -Xmx3200m
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - attach_workspace:
          at: ~/project
      - run: sudo apt-get update
      - run: sudo apt-get install -y --fix-missing imagemagick 
      - run: npm install
      - run: BUILD_NUM=$CIRCLE_BUILD_NUM ./scripts/version.sh
      - run: bundle install
      - run: bundle exec fastlane android build
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./artifacts/android
      - store_artifacts:
          path: ~/project/artifacts/android
      - store_test_results:
          path: ~/project/android/reports

  ios:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/project
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      FL_OUTPUT_DIR: /Users/distiller/project/output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout:
          path: /Users/distiller/project
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      # Not using a workspace here as Node and Yarn versions
      # differ between the macOS image and the Docker containers above.
      - run: brew install imagemagick
      - run: BUILD_NUM=$CIRCLE_BUILD_NUM ./scripts/version.sh
      - run: make ios
      # Disabling test report stuff for now.
      # - run:
      #  command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/results.xml || true
      #  when: always
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./artifacts/ios
      - store_artifacts:
          path: /Users/distiller/project/artifacts/ios
      - store_test_results:
          path: /Users/distiller/project/output/scan

  # Pushes the built app artifacts to testfairy.
  release-alpha:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: make upload-alpha

workflows:
  version: 2
  node-android-ios:
    jobs:
      - build
      - android:
          requires:
            - build
      - ios:
          requires:
            - build
      - release-alpha:
          requires:
            - ios
            - android
          filters:
            branches:
              only: master
      # - release-beta:
          # requires:
            # - ios
            # - android
          # filters:
            # tags:
              # # We release to testfairy if we have any new semver tag.
              # only: /^[v]?\d+.\d+.\d+/
            # branches:
              # ignore: /.*/
