# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GameBoard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameBoard

  # Google SignIn - used by react native google sign in.
  pod 'GoogleSignIn', '~> 4.4.0'

  # RNFirebase modules - it is recommended to pin them to a version. The full set
  # is here so that we can quickly uncomment as needed.
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Functions', '~> 5.20.1'
  pod 'Firebase/DynamicLinks', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Invites', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/RemoteConfig', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  pod 'Firebase/Performance', '~> 5.20.1'

  target 'GameBoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GameBoard-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameBoard-tvOS

  target 'GameBoard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
